export { Avatar } from './Avatar'
export type { AvatarColor, AvatarProps } from './Avatar'
export { StatusBadge } from './StatusBadge'
export type { FichaStatus, StatusBadgeProps } from './StatusBadge'
export { Button } from './Button'
export type { ButtonProps, ButtonSize, ButtonVariant } from './Button'
export { IconButton } from './IconButton'
export type { IconButtonProps, IconButtonVariant } from './IconButton'
export { Input } from './Input'
export type { InputProps } from './Input'
export { Card } from './Card'
export type { CardProps } from './Card'
export { EmptyState } from './EmptyState'
export type { EmptyStateProps } from './EmptyState'
export { PatientAvatar } from './PatientAvatar'
export type { PatientAvatarPatient, PatientAvatarProps } from './PatientAvatar'
